version: "3.9"
services:
  clothing-classifier: # tf-serving model
    image: clothes-classifier:v1
  gateway: # flask gateway service
    image: clothes-gateway:v2 # new version
    environment:
      - TF_SERVING_HOST=clothing-classifier:8500 # look for clothing model and port 8500
    ports: # map host machine with gateway
      - "9696:9696"